
$(warning "this is exec makefile file")

filetype=".pro"
normal_dirs=common widget vediodecoder audiodecoder playertype filemanager plugin
$(warning "normal_dirs=" $(normal_dirs))


ROOTDIR=$(PWD)
$(warning $(ROOTDIR))


include Makerules
