
$(warning "this is exec makefile file")

filetype=".pro"
normal_dirs=audiofiledecode audioplaymanager
$(warning "normal_dirs=" $(normal_dirs))


ROOTDIR=$(PWD)
$(warning $(ROOTDIR))


include Makerules
