
$(warning "this is exec makefile file")

filetype=".pro"
normal_dirs=qtplayer musicplayer vediomonitor desktopcapture pictureprocessor rtmplive awakened
$(warning "normal_dirs=" $(normal_dirs))


ROOTDIR=$(PWD)
$(warning $(ROOTDIR))


include Makerules
