
$(warning "this is exec makefile file")

normal_dirs=lib musicplay datapackage vediorecorde application
$(warning "normal_dirs=" $(normal_dirs))


ROOTDIR=$(PWD)
$(warning $(ROOTDIR))


include Makerules
